version:  3.8

services:
  python-app:
    build: .
    container_name: python-app
    ports: 
      - "9000:9000"  
    networks:
      - app-network

  nginx:
    image: nginx:1.17.1-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf /etc/nginx/nginx.conf
    depends_on:              # it ensures the python-app container starts before the nginx container.
      - python-app
    networks:
      - app-network

networks:
  app-network:
  driver: bridge  
